# .github/workflows/auto-merge.yml

name: Auto-merge Infrastructure PRs

on:
  repository_dispatch:
    types: [auto-merge-pr]

# IMPORTANT: Add proper permissions for PR merging
permissions:
  contents: write        # Required to merge PRs
  pull-requests: write   # Required to manage PRs
  actions: read          # Standard read access

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR
        run: |
          gh pr merge ${{ github.event.client_payload.pr_number }} \
            --repo ${{ github.repository }} \
            --squash \
            --delete-branch
        env:
          # Use GitHub token with enhanced permissions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          